# Site settings
title: pictures | stefan 
baseurl: "/photography-site" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Stefan Hermanek

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/iamstefanh/
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/stefanhermanek

# Build settings
markdown: kramdown
